### ISSUE TITLE
menu link - single k2 category listing does not follow the category choosen template

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#40]
Hello, thanks again for this marvelous fork! 
When I create menu link to a single k2 category, expected is that the template for the listing obeys the choice selected in the category display settings - a sub-template created in templates/mytemplate/html/com_k2/mysubtemplate.
The result is - call of the default template, and none of the display settings set in the category obeyed (no images, no extra fields displayed although they are set to show).   
When multi-categories are set in the menu settings, and a template is chosen in the menu settings, then everything goes according the expected behavior.

**Comment by eworkers** [comment]
does this dc87567 solve your issue?

**Comment by eworkers** [comment]
please note that you have to edit and save the menu item again

**Comment by eworkers** [comment]
fixed in dc87567

**Comment by krmrtrzv** [comment]
Thanks! I applied the two changes in
administrator/components/com_k2/elements/k2category.php
and components/com_k2/router.php
Opened the menu link pointing to single category, edited it an save it, as
recommended, but the issue is still there - the selected category template
is not applied to the view, the default template is applied instead.

**Comment by eworkers** [comment]
> link

is cache enabled? if so try to clear the cache and report back please, if not please open a new issue and we will take a look

**Comment by krmrtrzv** [comment]
Here is a link to the wrong menu: https://terziev.info/en/works2/category/4
Cache is disabled, browser cache is, JCH component and plugin are disabled.
Please suggest if I need to open a new issue
